### ISSUE TITLE
Best way to remove old splat scene from the view?

### ISSUE THREAD

**Issue by pesa2000** [mkkellogg/GaussianSplats3D#183]
Hello Mark, first of all, happy Easter.

I am conducting a series of performance tests on a single viewer where I can select different splat files and render them in the same viewer one at the time, each one of them is loaded using the addSplatScene method.

I have noticed that the more splats I load, the more the page's performance drops, as if the viewer continues to calculate old scenes.

When changing splats, I have also implemented a function that completely clears the three.js scene that the viewer is using at that moment, but the performance drop continues to be present.

Do you think there could be some sort of bottleneck somewhere? Or is there a function in your code that I could leverage to say "reset/clear" the loaded scene?

Thank you very much for your time, have a great day!

**Comment by mkkellogg** [comment]
I plan on adding a function to remove a splat scene in one of the upcoming releases, but in the meantime you can unload and dispose of all resources by calling `Viewer.dispose()`. Once you call `Viewer.dispose()` that instance of `Viewer` should be considered permanently invalid. For loading any more scenes after the call to `dispose()` you'd want to create a new instance of `Viewer` first.

**Comment by pesa2000** [comment]
Perfect, thank you very much, i will wait the next releases for the function.

**Comment by pesa2000** [comment]
Hello Mark, sorry to bother you again.
I am taking the opportunity by writing in this ticket.

Do you know if there are actually some methods to use a Semantic Mask for splat scenes? If it is possible, would you consider implementing something about it in the future?

**Comment by mkkellogg** [comment]
At some point I think it would be really cool to add some semantic segmentation (guided and/or automatic), but to some extent I think offline tools are better for that purpose (or perhaps something that is integrated into the training process). Otherwise the segmentation code has to run in the browser, and for currently available methods that is pretty slow. Possibly someday with something like WebGPU it could be made reasonably fast :)

BTW I added a function to remove splat scenes in the latest release: `Viewer.removeSplatScene()`. It's a bit slow for larger scenes, so it is not meant to be used super frequently.

**Comment by pesa2000** [comment]
Hi Mark, first of all thank you for the fast reply, the release of the method and for the explanation regarding the Semantic Mask.

I'm having some difficulties when removing the scene, before loading the next one i am calling the removeSplatScene with index 0(i add only one scene at the time), when i call the function an error is thrown.

I placed a log on this line to see if the scene was indeed present in the array

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/36411479/64a13138-571e-418c-946c-d9c7404fc1f3)

The error trace and the logs of the scenes array are the following: 

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/36411479/cc0fb81c-d3ae-4a39-9698-d155567e7c8a)

Am i doing something wrong? 

Thank very much have a great weekend.

**Comment by mkkellogg** [comment]
You're not doing something wrong, there were definitely some bugs in there :) I pushed some fixes to my `dev` branch, would you be able to try that out to see if it works for you?

**Comment by pesa2000** [comment]
Hi Mark thank you for the fast reply, i cloned the repo and swicthed to the dev branch, after building it the code doesnt throw new errors and the promise is resolved correclty.

On pc seems to work fine(probably related to better hardware) but on mobile (Iphone 15 Pro Max) im still having problems, the more scenes i load (always one at the time), the more the page lag, even if before adding a new splat i am calling the viewer.removeSplatScene(0, false).

The strange thing is that when i log the splatMesh object the scenes inside are empty so unless something wasnt disposed correctly it should work.

I also tried a different thing, i disposed the entire viewer and created a new one before loading a new scene and the same thing happens.

P.S i found a strange bug always related to switching scenes inside the viewer, the more scenes i load the faster the camera orbit becomes even if i am not changing it during the entire session. 

Thank very much for your precious help, have a great weekend.

**Comment by jvandereijk** [comment]
Thank you Mark for the new release. When reading the comment above, I just want to mention that I had the same issues a couple of weeks ago on an iphone 12 mini. Using dispose and then loading a new splat made it slower and also the rotation was going faster. I couldn't isolate the problem then and just refreshing the page when loading a new splat was pretty fast, so I went that route for now. I was hoping the new removeSplatScene method would have fixed it so I could give it another try keeping it single page, but it looks like maybe the scene or the webworkers aren't 100% disposed somehow ?

**Comment by mkkellogg** [comment]
I ran some tests locally and I am seeing the same issue. I will investigate and get back to you when I have a solution or at least when I know what the problem is.

**Comment by mkkellogg** [comment]
Would either of you be able to share the code you used to reproduce this issue?

**Comment by pesa2000** [comment]
Hi Mark, 

https://pastecode.io/s/p0nbwror

this is a custom html element made to help me switch trough scenes, for doing so i place the custom tag element directly in the html and when you want to switch scene just change the src of the element itself(something like google's model-viewer).

I've added a couple of comments in the main methods used for loading and deleting the scenes.

<viewer-splat id="viewer" class="model-viewer opacity-component" height="900px" width="100vw" 
          shadow-intensity="1" camera-orbit="165deg 55deg 1.5m" camera-target="0m 0m 0m" exposure="1" 
          max-camera-orbit="auto 85deg auto" src=""
        >
        </viewer-splat>
        
i am using it like so even tho a lot of attributes are uselles for a splat scene(dont mind them).

Let me know if you need something else.

Have a great day.

**Comment by mkkellogg** [comment]
So it looks like every time you call `loadModel()`, it will call `requestAnimationFrame(this.updateFrame);`... are you making sure to call `cancelAnimationFrame()` before that? You might be requesting excessive render callbacks.

**Comment by pesa2000** [comment]
Oh got it, i didnt even tought about that, this also fixes my problems with multiple updates of the orbit controls.

Related to the rendering on mobile browsers do you have any advice for that? like some attributes that can be changed in the viewer settings for example? 

Sorry for wasting you time, thank you very much for your help.

**Comment by mkkellogg** [comment]
For mobile browser rendering it's a bit tougher, they just have a hard time rendering all those splats. You can experiment with the `splatAlphaRemovalThreshold` parameter to the `addSplatScene()` function which will discard splats below the given alpha value. Or try editing your splat scenes in PlayCanvas' SuperSplat editor (https://playcanvas.com/supersplat/editor) to clean them up and reduce the total number of splats. Really the best thing to do to increase performance is reduce the number of splats :)

**Comment by mkkellogg** [comment]
I'll close this one for now. At some point in the future, I hope to refine the splat removal process and make it faster :)

**Comment by pesa2000** [comment]
Sorry didnt saw the last messages, works perfectly now, thank you very much for your advices.
