### ISSUE TITLE
Questions about dynamically loading data

### ISSUE THREAD

**Issue by Linkersem** [mkkellogg/GaussianSplats3D#273]
Hello, thank you for your excellent work, I have 5 ply data (A, B, C, D, E), I load three ply at once, when my camera moves to scene C, I want to be able to load the ply of scene D and delete the data of scene A, what should I do?

**Comment by mkkellogg** [comment]
You can use `Viewer.removeSplatScene(<scene index>)` , which returns a promise, to remove a splat scene and when that call completes you can load a different splat scene using `Viewer.addSplatScene()`

**Comment by Linkersem** [comment]
thx for your reply! i will try it and give a response.

**Comment by Linkersem** [comment]
Hi, @mkkellogg 
I tried what you said, he can delete the scene I don't need when rendering, but the whole page will turn black when deleting, is this normal? What should I do so that when I delete scene data, the entire page does not go black? For example, when I'm in scene C, I want to delete scene A, but it shouldn't affect what I'm looking at at scene C at that moment.
Thx for your greate work!

**Comment by Linkersem** [comment]
And i also want to ask how to delete multiple scenes ?

**Comment by mkkellogg** [comment]
Well most likely you're still rendering while the scene removal or scene addition is in process. If you post your code I can help fix it, but you need to make sure not to render until the promises returned by `Viewer.removeSplatScene(<scene index>)` or `Viewer.addSplatScene()` complete.

As for deleting multiple scenes, there is not a great way to do that unfortunately. The only way is to make multiple calls to `removeSplatScene()` (one at a time of course).

**Comment by mkkellogg** [comment]
I will try to add a `removeSplatScenes()` function to the next release to remove multiple splat scenes at once.

**Comment by Linkersem** [comment]
Ohhh，thx for your reply!
Regarding the black screen issue after deleting scenes, I may be able to provide some useful code snippets this week, regarding the case of deleting multiple scenes, I am calling this function multiple times now, looking forward to your update. 
But I have some confusion. For example, when I delete scene A, I do not delete scene C. So theoretically, scene C should still be rendering. Therefore, I do not understand your statement, "you're still rendering while the scene removal or scene addition is in process."

**Comment by mkkellogg** [comment]
Well `Viewer.addSplatScene()` actually works by removing all of the scenes, clearing out all of the viewer's resources, and then adding the scenes you want to keep back in. That's why you see black for a small amount of time if you keep rendering while that function is executing.

**Comment by Linkersem** [comment]
Hahaha, then what should I do to achieve the purpose I am talking about? Thank you again for your patient reply!

**Comment by mkkellogg** [comment]
Well during the call to `removeSplatScene()`, you need to make not to call the `render()` function of whatever three.js renderer you are using.

Here's an example of how it might work, where a function `removeScene()` could be called to remove a scene:

```
// main animation loop
let renderPause = false;
requestAnimationFrame(update);
function update() {
  requestAnimationFrame(update);
  if (!renderPause) {
    // renderer = three.js WebGLRenderer
    // threeScene is the three.js Scene instance
    renderer.render(threeScene, camera);
  }
}

const removeScene = () => {
  renderPause = true;
  viewer.removeSplatScene(0).then(() => {
    renderPause = false;
  });
);

```

**Comment by lucylucy27** [comment]
Hi All，
I encountered the same black screen issue. It seems that the renderPause was not able to avoid this black screen problem. My code logic is: 
1. add blk0 and blk1, then stay at the position of blk0. 
2. After waiting for a mouse event, trigger the removal of blk1 and the addition of blk2, and set renderPause to true. 
3. After another 15 seconds, set renderPause to false. During this period, remain at the position of blk0. 
I noticed that the screen suddenly changed to black after a period of time（15s after loding blk2 finished in my experiment), and then gradually recovered to normal. It seems that this black screen is something that the upper-level code cannot avoid. 
It would mean so much if a solution could be found., the user experience will be much better.  :)

Thx for your pacience!

**Comment by lucylucy27** [comment]
[sample.txt](https://github.com/user-attachments/files/16104615/sample.txt)

Here attached my sample.

**Comment by mkkellogg** [comment]
Would you both be able to post your full source code for me to debug? @lucylucy27 The code you posted is incomplete and cannot be run.

**Comment by Linkersem** [comment]
Hi, @mkkellogg here is my test code, I encountered two problems, one is that I used the method you mentioned above to avoid the black screen when deleting the scene, but it doesn't seem to work, and the other is that I can delete a single scene, but I only encountered an error when deleting multiple ones,Is there something wrong with my operation?

> "Error: Cannot remove splat scene while another load or unload is already in progress.
>     at Viewer.removeSplatScene (Viewer.js:1250:19)
>     at DropInViewer.removeSplatScene (DropInViewer.js:89:28)
>     at bonsai.html?mode=1:133:54
>     at Array.map (<anonymous>)
>     at removeScene (bonsai.html?mode=1:133:26)
>     at update (bonsai.html?mode=1:147:9)”

**Comment by Linkersem** [comment]
Hi, @mkkellogg here is my test code, I encountered two problems, one is that I used the method you mentioned above to avoid the black screen when deleting the scene, but it doesn't seem to work, and the other is that I can delete a single scene, but I only encountered an error when deleting multiple ones,Is there something wrong with my operation?
[bonsai.txt](https://github.com/user-attachments/files/16118580/bonsai.txt)


> "Error: Cannot remove splat scene while another load or unload is already in progress.
> at Viewer.removeSplatScene (Viewer.js:1250:19)
> at DropInViewer.removeSplatScene (DropInViewer.js:89:28)
> at bonsai.html?mode=1:133:54
> at Array.map ()
> at removeScene (bonsai.html?mode=1:133:26)
> at update (bonsai.html?mode=1:147:9)”

**Comment by mkkellogg** [comment]
@Linkersem The reason you're seeing the error is you're making 2 simultaneous calls to `Viewer.removeSplatScene()`. You need to wait until the call for that function finishes for one scene before calling it on another scene.

As for the black screen, I think I know why it is happening and it's due to a small bug with the `DropInViewer`. I will try to get a fix for it soon.

**Comment by Linkersem** [comment]
Ohh,Thanks for the reply, I also tried to call the Viewer.removeSplatScene() function with an asynchronous operation, but the problem with this is that the delete operation seems to be invalid, my function is like this:

>     async function removeMultipleScenes(viewer, sceneIds) {
>       console.log("start removeMultipleScenes");
>       for (let sceneId of sceneIds) {
>         await viewer.removeSplatScene(sceneId).catch(error => {
>           console.error(`Error removing scene ${sceneId}:`, error);
>           // Optionally, you might decide to throw an error or continue with the next scene
>           throw error; // This will stop the execution of further removals if one fails
>         });
>       }
>     }
and Here's what I called:                    

>           renderPause = true;
>           removeMultipleScenes(viewer, scenesToRemove)
>             .then(() => {
>               console.log('Removed scenes okay');
>               renderPause = false;
>               viewer.addSplatScenes(newScenes);
>             })
>             .catch(error => {
>               console.error('Error adding new scene:', error);
>             });
When the variable scenesToRemove contains only one variable, such as scenesToRemove=[0], it can delete the scene normally, but when scenesToRemove=[0,1] it does not work properly. I'm very confused about this.

and Looking forward to your fix of black screen.

**Comment by mkkellogg** [comment]
I actually added a function `removeSplatScenes` for multiple concurrent deletions :) It takes an array of indexes corresponding to scenes you want to remove. I also fixed the `DropInViewer` bug (I think). Both updates are now in the `2dgs` branch if you want to try them out.

**Comment by Linkersem** [comment]
Thx for your great work,I tried your new code, it works for deleting multiple scenes, but it seems that there is still a black screen when deleting, this is my test code, is there a problem?
[bonsai.txt](https://github.com/user-attachments/files/16130757/bonsai.txt)

**Comment by Linkersem** [comment]
Wow! That's OK, thank you very much for your patience and help.

**Comment by Linkersem** [comment]
Hello, @mkkellogg I encountered a new black screen problem, I delete the scene and then reload the scene will still have a black screen phenomenon, this is my code, how to solve this situation?
[bonsai.txt](https://github.com/user-attachments/files/16143616/bonsai.txt)

**Comment by mkkellogg** [comment]
So the problem is that you're trying to use this viewer in ways I never planned on it being used 😄  It's not well set up for rapid scene removal and addition. One of the issues is after a call to `Viewer.addSplatScenes()` or `Viewer.removeSplatScenes()`, the viewer is building an octree in the background for things like raycasting, and if you quickly try to remove or add a scene again, it collides with the ongoing octree construction. There is a way to synchronize with the completion of octree construction, so one way to handle it (it's a bit hokey) would be to do this:
```
if(count == 1000){
  renderPause = true;
  var list = [0,1];
  viewer.removeSplatScenes(list).then(() => {
    viewer.splatMesh.onSplatTreeReady(() => {
      viewer.splatMesh.onSplatTreeReady(null);
      renderPause = true;
      viewer.addSplatScenes([        
      {
        'path': 'assets/data/garden/garden_high.ksplat',
        'splatAlphaRemovalThreshold': 20,
      },
      {
        'path': 'assets/data/stump/stump_high.ksplat',
        'rotation': [-0.14724434, -0.0761755, 0.1410657, 0.976020],
        'scale': [1.5, 1.5, 1.5],
        'position': [-3, -2, -3.2],
        'splatAlphaRemovalThreshold': 20,
      },
      ]).then(() => {
        renderPause = false;
      });
    });
    renderPause = false;
  });
}
```

**Comment by Linkersem** [comment]
ohhhh! I see what you mean, I tried the solution you gave and it works, thank you so much for your help, you're soooooo nice, I've also noticed that the process seems to be a little bit long (loading scenes after deletion), do you have any plans to optimize this? If not, could you please tell me how to do it? I want to give it a try.

**Comment by Linkersem** [comment]
> Well `Viewer.addSplatScene()` actually works by removing all of the scenes, clearing out all of the viewer's resources, and then adding the scenes you want to keep back in. That's why you see black for a small amount of time if you keep rendering while that function is executing.

Hi @mkkellogg ,I made some attempts to delete those scenes I wanted to delete directly to avoid deleting everything inside the scenes, because they would cause a black screen and stuttering, but it doesn't seem to work. I am confused, so I want to ask for your help.
and this is my code.


>                for (let i = 0; i < this.splatMesh.scenes.length; i++) {
>                     let shouldRemove = false;
>                     for (let indexToRemove of indexesToRemove) {
>                         if (indexToRemove === i) {
>                             shouldRemove = true;
>                             break;
>                         }
>                     }
>                     if (shouldRemove) {
>                         this.splatMesh.scenes[i] = [];
> 
>                     }
>                 }
>                 this.splatMesh.updateTransforms();
>                 this.updateSplatSort(true)
>                     .then(() => {
>                         checkAndHideLoadingUI();
>                         resolve();
>                     })
>                     .catch(error => {
>                         checkAndHideLoadingUI();
>                         reject(error);
>                     });

In addition to this, I also noticed that the addsplatscenes function also has a black screen for a moment, but I didn't find where it deleted the whole scene.

**Comment by mkkellogg** [comment]
Wow I just realized I never responded to this one... did you get this sorted out?

**Comment by PraveenSekar-official** [comment]
Hi @mkkellogg, Thanks for your contribution on the Gaussian Splat viewer.

I have few queries on the topics discussed above.

Requirement:  I have large ply data which is divided into multiple small chunk plys. These ply chunks will be loaded in the three.js scene, based on the change in viewpoint.

For each change roughly 150 to 200 ply files will be loaded using addSplatScenes().  I observe that loading these plys takes nearly 5 seconds to complete.

I tried different approach to solve this issue, but it didn't help. Example: Loading plys by iterative manner, addSplatScene()
As discussed above, rapid scene removal and addition is not possible in the viewer. 

Question1: Could you suggest any method to reduce the time delay in the usecase like multiple ply files in a single update.

Question2: While loading the ply file, you recommened to pause the redender to avoid black screen issue. 
But we noticed that, during pause(upto 1second), the screen becomes unresponsive. Please suggest any solution for this.
